server.port=${PORT:4000}
spring.data.mongodb.uri=${MONGO_URI}
spring.data.redis.url=${REDIS_URL:redis://127.0.0.1:6379}
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
spring.jackson.time-zone=UTC
server.forward-headers-strategy=none
